export const SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS providers (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    display_name TEXT NOT NULL,
    enabled INTEGER NOT NULL,
    healthy INTEGER NOT NULL DEFAULT 0,
    last_checked_at TEXT,
    avg_latency_ms REAL,
    failure_count INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}'
  )`,
  `CREATE TABLE IF NOT EXISTS models (
    id TEXT PRIMARY KEY,
    model_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    context_window INTEGER,
    max_output_tokens INTEGER,
    capabilities_json TEXT NOT NULL,
    pricing_json TEXT NOT NULL,
    free_tier INTEGER NOT NULL,
    scores_json TEXT NOT NULL,
    health_state TEXT NOT NULL,
    latency_ms REAL,
    reliability REAL NOT NULL,
    requests_remaining INTEGER,
    tokens_remaining INTEGER,
    reset_at TEXT,
    raw_json TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(provider_id) REFERENCES providers(id)
  )`,
  `CREATE TABLE IF NOT EXISTS quotas (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL,
    model_id TEXT,
    kind TEXT NOT NULL,
    limit_value INTEGER,
    used_value INTEGER,
    remaining_value INTEGER,
    reset_at TEXT,
    exhausted_until TEXT,
    cooldown_until TEXT,
    raw_json TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS usage_events (
    id TEXT PRIMARY KEY,
    request_id TEXT NOT NULL,
    provider_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    task_type TEXT NOT NULL,
    prompt_tokens INTEGER NOT NULL,
    completion_tokens INTEGER NOT NULL,
    total_tokens INTEGER NOT NULL,
    latency_ms REAL NOT NULL,
    success INTEGER NOT NULL,
    error_code TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS health_events (
    id TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL,
    healthy INTEGER NOT NULL,
    latency_ms REAL,
    error TEXT,
    checked_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS routing_history (
    id TEXT PRIMARY KEY,
    request_id TEXT NOT NULL,
    task_type TEXT NOT NULL,
    selected_provider_id TEXT,
    selected_model_id TEXT,
    candidates_json TEXT NOT NULL,
    reason TEXT NOT NULL,
    success INTEGER NOT NULL,
    error TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_models_provider ON models(provider_id)`,
  `CREATE INDEX IF NOT EXISTS idx_usage_provider_model ON usage_events(provider_id, model_id)`,
  `CREATE INDEX IF NOT EXISTS idx_usage_created ON usage_events(created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_quotas_provider_model ON quotas(provider_id, model_id)`
] as const;
